### ISSUE TITLE
dataset processed

### ISSUE THREAD

**Issue by pengqianhan** [TeCSAR-UNCC/Pishgu#1]
Could you please explain how you downsample the NGSIM dataset? The original framerate of NGSIM is 10Hz. How do you process the dataset to reduce it to 5Hz while ensuring that the frame ID remains continuous?

**Comment by vinit-katariya** [comment]
The preprocessing of NGSIM is done as discussed in https://arxiv.org/pdf/1805.06771.pdf. This was done for maintaining  consistency in comparing the results of previous works.

**Comment by vinit-katariya** [comment]
The preprocessing of NGSIM is done as discussed in https://arxiv.org/pdf/1805.06771.pdf. This was done for maintaining  consistency in comparing the results of previous works. You can find the preprocessing code here (https://github.com/nachiket92/conv-social-pooling).

**Comment by guoyage** [comment]
> The preprocessing of NGSIM is done as discussed in https://arxiv.org/pdf/1805.06771.pdf. This was done for maintaining  consistency in comparing the results of previous works. You can find the preprocessing code here (https://github.com/nachiket92/conv-social-pooling).

However, we found that the data preprocessing code you mentioned does not contain the data downsampling operation, so how do you downsample the data? Because the sampling frequency of your data can be fatal to your results.

**Comment by guoyage** [comment]
> Could you please explain how you downsample the NGSIM dataset? The original framerate of NGSIM is 10Hz. How do you process the dataset to reduce it to 5Hz while ensuring that the frame ID remains continuous?

Are you puzzled by the small results presented in the paper?

**Comment by vinit-katariya** [comment]
We will look into it and get back to you.

**Comment by guoyage** [comment]
> We will look into it and get back to you. 

What are the results of your investigation? I am looking forward to your reply.
